"""Replaced creation datetime with last modififed

Revision ID: b2dbb32b4c89
Revises: d72b191ed098
Create Date: 2025-09-17 19:22:47.955460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2dbb32b4c89'
down_revision = 'd72b191ed098'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_modified', sa.DateTime(), nullable=False))
        batch_op.drop_column('creation_datetime')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creation_datetime', sa.DATETIME(), nullable=False))
        batch_op.drop_column('last_modified')

    # ### end Alembic commands ###
